config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get 'resume' => 'static_pages#resume'
  get 'mission' => 'static_pages#mission'
  get 'simular' => 'static_pages#simular'
  get 'languages' => 'static_pages#languages'
  get 'fsd' => 'static_pages#fsd'
  get 'code' => 'static_pages#code'
  get 'aws' => 'static_pages#aws'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'edit' => 'edit#new'
  get 'four_oh_four' => 'static_pages#home'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  #This is a catchall for 404's
  match '*_path', to: 'static_pages#home', :via => 'get'

end

#
# The priority is used upon order of creation: first created -> highest priority.
# See how all your routes lay out with "rake routes".

# You can have the root of your site routed with "root"

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def mission
  end

  def simular
  end

  def languages
  end

  def fsd
  end

  def code
  end

  #  unless logged_in?
  #    flash[:info] = "Please login to view the code page"
  #    redirect_to login_url
  #  end
  # end


  def resume
    #   unless logged_in?
    #     flash[:info] = "Please login to view the resume page"
    #     redirect_to login_url
    #   end
  end

  def about
  end

  def contact
  end

  def four_oh_four
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'Employer Introduction Site - About') %>


<div class="jumbotron" style="background:#FFFFE0 !important">

<h1>About Mark Hanna</h1>
<p>
  I will fill this out later. Edit with ...
</p>


</div>

app/views/static_pages/aws.html.erb
<% provide(:title, 'Employer Introduction Site - AWS') %>

<div class="jumbotron" style="background:#FFFFE0 !important">

  <h3 align="center" style="color:#000000">Amazon Web Services</h3>

  <p align="justify">The purpose of this site is to demonstrate proficiency in cloud administration and Ruby on Rails.
    In this case the cloud is Amazon Web Services.</p>

  <p align="justify">This Ruby on Rails application is hosted on an Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic
    x86_64) EC2 instance. The native AWS instance domain name is
    <a href="http://ec2-52-7-56-224.compute-1.amazonaws.com/mission" style="color:#000000">http://ec2-52-7-56-224.compute-1.amazonaws.com</a>.
    The <a href="http://actually-qualified.com/mission" style="color:#000000; text-decoration: underline;">http://actually-qualified.com</a>
    domain name is routed
    using AWS "Route 53" service. Being able to click on a link whose top level domain is amazonaws.com proves
    that the site is hosted on the Amazon AWS cloud service.
  </p>

  <h3 align="center" style="color:#000000">I Love Amazon Web Services.</h3>

  <p align="justify">AWS is the wave of the future. Hosting your own computers is no longer the way to go.</p>

  <p align="justify">Cloud Case Study ... Zynga and Amazon Web Services</p>

  <p align="justify">Zynga is a massive online game site.

    In 2012 Zynga moved from a pure public cloud model using AWS,
    to a hybrid model called zCloud.
    Zynga chose to complement (i.e. mostly replace) Amazon with its own internal data center.
    Regardless of the company, industry or vertical Zynga's zCloud was a massive-scale operation.
    Zynga thought they would realize significant management efficiencies and substantially
    reduced costs from zCloud.</p>

  <p align="justify">To set some context around the massive scale we are talking about, here are some pretty
    incredible business metrics around the adoption of Zynga and social gaming.

  <ul>
    <li>Zynga has >250m monthly active users globally.
    <li>It has developed seven of the top 10 games on Facebook.
    <li>Five new players join Zynga every second.
    <li>Ten percent of the world's Internet population plays Zynga games every month.
    <li>Cityville went from 0 to 100m users in 40 days.
    <li>If Farmville were a country, it would be the fifth largest in the world.
    <li>One in five Americans play social games.
    <li>Farmville was the inflection point in Zynga's business. The game grew to 25m daus (daily active users) in five
      months.
    <li>RightScale is a very important component of the infrastructure, across both the public and private cloud
      implementations, for scale, flexability, provisioning and monitoring.
    <li>Zynga built it's own private cloud, the zCloud (internal Zynga private cloud):
    <li>When the game growth slope is vertical, it can’t build fast enough.
    <li>When growth is less than vertical, it can build the system to meet this demand.
    <li>zCloud uses industry-standard servers and hypervisors (xen, kvm).
    <li>zCloud creates Amazon-like security zones.
    <li>zCloud's infrastructure is integrated with RightScale.
    <li>The zCloud works on an IP routed network and is required to automatically scale,
      it just doesn’t scale on layer 2 switches.
  </ul>
  <h3 align="center" style="color:#000000">2015 Zynga dismantles zCloud</h3>

  <p align="justify">
    In May 2015 it was announced that after spending over $100 million dollars Zynga is abandoning their own data
    centers. Zynga is moving back to 100% Amazon Web Services as a cost cutting move. This move unfortunately
    will cost over 300 people their jobs at Zynga.
    Zynga is now considered the poster child for Amazon Web Services client retention efforts.

  </p>

  <p align="justify">
    If your company is already using Amazon Web Services then you made a very smart choice.
    If not and you are now thinking about it. I would
    love to help you in the transition and operation of your cloud based solutions.
  </p>

  <p align="justify">The link in the lower left corner of this page will lead you to the latest news about Amazon Web
    Services</p>

  <br><br><br>Zynga facts were taken from the various web sources including ...&nbsp;http://www.datacenterdynamics.com/app-cloud/zynga-abandons-data-centers-returns-to-aws/93952.fullarticle

</div>

app/views/static_pages/code.html.erb
<% provide(:title, 'Employer Introduction Site - Use The Right Tool for the Job') %>

<div class="jumbotron" style="background:#FFFFE0 !important">

  <h3 align="center" style="color:#000000">Use The Right Tool for the Job</h3>

  <p align=left>Our brains are impressive at cracking codes.</p>

  <p align=justify>We use context to pre-activate the areas of our brains that correspond to what we expect next.</p>

  <p align=justify>You might not realize it, but your brain is a code-cracking machine.</p>

  <table width="100%" style="background:#faebd7"><tr><td>
  <mixedupletters>

    For emaxlpe, it deson't mttaer in waht oredr the ltteers in a wrod aepapr,<br>

    The olny iprmoatnt tihng is taht the frist and lsat ltteer are in the rghit pcale.<br>

    The rset can be a toatl mses and you can sitll raed it wouthit pobelrm.<br>

    S1M1L4RLY, Y0UR M1ND 15 R34D1NG 7H15 4U70M471C4LLY W17H0U7 3V3N 7H1NK1NG 4B0U7 17.

  </mixedupletters>
  </td></tr></table>
  <br>
  <p align=justify>Passages like these have been bouncing around the Internet for years. But how do we read them? And
    what do our incredibly low standards for what's legible say about the way our brains work? It shows that you have
    been reading the english language for a very long time and you sort of know what context words are used in.</p>

  <p align=justify>Computer coding is very simular. After a long while a it all looks sort of the same.</p>

  <h1><%= link_to 'In order to see just how simular Click Here', simular_path  %></h1>

  <br><br><br><br><br><br><br><br>

</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Employer Introduction Site - Contact') %>

<div class="jumbotron" style="background:#FFFFE0 !important">
<h1>Contact Info</h1>


<h3 align="center" style="color:#000000">Mark Hanna</h3>
<h3 align="center" style="color:#000000">5072 Springdale Road</h3>
<h3 align="center" style="color:#000000">Cincinnati, Ohio 45251</h3>
<h3 align="center" style="color:#000000">Mobile: (513) 570-7683</h3>
<h3 align="center" style="color:#000000">Email: <a href="mailto:mhanna500@gmail.com">mhanna500@gmail.com</a></h3>
<h3 align="center" style="color:#000000">
  <a href="https://www.linkedin.com/in/actuallyqualified" target="_new"><%= image_tag 'Linkedin-logo.png' %></a>
  <a href="https://www.facebook.com/mark.hanna.5492" target="_new"><%= image_tag 'facebook-icon.png' %></a>
  <a href="https://twitter.com/BigDaddyCinti" target="_new"><%= image_tag 'twitter.png' %></a></h3>

</div>

app/views/static_pages/fsd.html.erb
<% provide(:title, 'Employer Introduction Site - Full Stack Developer') %>

<div class="jumbotron" style="background:#FFFFE0 !important">

  <h1>Full-Stack Developer</h1>

  <p align="justify">It is always tough to apply self-reflection and ask who am I? So I did some research
    into current job titles and the qualifications associated with each. I came across the
    description of the full stack developer.</p>


  <p align="justify">Am I a “full-stack developer”? Varying definitions of this title exist: from a developer
    specialized in everything from front-end to back-end; to a developer who has a general
    knowledge in all steps from concept to finished product; to a fictional figure with a
    virtually unattainable skill set.</p>

  <p align="justify">To me, a Full Stack Developer is someone with familiarity in each layer, if not
    mastery in some and a genuine interest in all software technology.</p>

  <p align="justify"><strong>Good developers who are familiar with the entire stack know how to make
    life easier for those around them. </strong>
  <ol>
    <li><strong>Server, Network, and Hosting Environment.</strong>
      <ol>
        <li>All software should either increase revenues and/or lower costs.</li>
        <li>This involves understanding what can break and why, taking no resource for granted.</li>
        <li>Appropriate use of the file system, cloud storage, network resources, and an
          understanding of data redundancy and availability is necessary.
        </li>
        <li>How does the application scale given the hardware constraints?</li>
        <li>What about multi-threading and race conditions? Guess what, you won't see those on
          your development machine, but they can and do happen in the real world.
        </li>
        <li>Full stack developers can work side by side with DevOps.
          The system should provide useful error messages and logging capabilities.
          DevOps will see the messages before you will, so make them count.
        </li>
      </ol>
    </li>
    <li><strong>Data Modeling</strong>
      <ol>
        <li>All software should either increase revenues and/or lower costs.</li>
        <li>If the data model is flawed, the business logic and higher layers will suffer.</li>
        <li>Full stack developers know how to create a reasonably normalized relational model,
          complete with foreign keys, indexes, views, lookup tables, etc.
        </li>
        <li>Full stack developers are familiar with the concept of non-relational data stores
          and understand where they shine over relational data stores.
        </li>
      </ol>
    </li>
    <li><strong>Business Logic</strong>
      <ol>
        <li>All software should either increase revenues and/or lower costs.</li>
        <li>The heart of the value the application provides.</li>
        <li>Solid object oriented skills are needed here.</li>
        <li>Frameworks might be needed here as well.</li>
      </ol>
    </li>
    <li><strong>API layer / Action Layer / MVC</strong>
      <ol>
        <li>All software should either increase revenues and/or lower costs.</li>
        <li>How the outside world operates against the business logic and data model.</li>
        <li>Frameworks at this level should be used heavily.</li>
        <li>Full stack developers have the ability to write clear, consistent,
          simple to use interfaces.
        </li>
      </ol>
    </li>
    <li><strong>User Interface</strong>
      <ol>
        <li>All software should either increase revenues and/or lower costs.</li>
        <li>Full stack developers: a) understand how to create a readable layout, or
          b) acknowledge they need help from artists and graphic designers. Graphics is a
          weakness of mine. I had an orange and black painted bathroom once.
          Either way, implementing a good visual design is key.
        </li>
        <li>Can include mastery of HTML5 / CSS.</li>
        <li>JavaScript and AJAX adds style. Lots of exciting work is being done in
          the JavaScript world.
        </li>
      </ol>
    </li>
    <li><strong>User Experience</strong>
      <ol>
        <li>All software should either increase revenues and/or lower costs.</li>
        <li>Full stack developers appreciate that users just want things to work.</li>
        <li>A good system doesn't give its users carpal tunnel syndrome or sore eyes.
          A full stack developer can step back and look at a process that needs 8 clicks
          and 3 steps, and get it down to one or two clicks.
        </li>
        <li>Full stack developers write useful error messages. If something breaks,
          be apologetic about it. Sometimes programmers inadvertently write error
          messages that can make people feel stupid.
        </li>
      </ol>
    </li>
    <li><strong>Understanding what the customer and the business need.</strong>
      <ol>
        <li>Now we are blurring into the line of architect,
          but that is too much of a hands off role.
        </li>
        <li>Full stack developers have a grasp of what is going on in the field when
          the customer uses the software. They also have a grasp of the business.
        </li>
        <li>All software should either increase revenues and/or lower costs.</li>
      </ol>
    </li>
  </ol>
  <p align="justify">&nbsp;</p>

  <p align="justify"><strong>Other Pieces of the Puzzle:</strong></p>
  <ol>
    <li>Ability to write quality unit tests. By the way, even JavaScript can have unit tests these days.</li>
    <li>Understanding of repeatable automated processes for building the application, testing it,
      documenting it, and deploying it at scale.
    </li>
    <li>An awareness of security concerns is important, as each layer
      presents its own possible vulnerabilities.
    </li>
  </ol>
  <p align="justify">&nbsp;</p>

  <p align="justify"><strong>Closing Thoughts:</strong></p>

  <p align="justify">If you read this closely you noticed that I repeated ... </p>
  <ul>
    <li>All software should either increase revenues and/or lower costs.</li>
  </ul>

  <p align="justify">I did so because I think that it is lost on too many in our field, that every action taken should
    be
    in an effort to add value by either providing people, processes and/or product
    which will either increase revenues and/or lower costs for the company or client.
    All other actions are waste.</p>

  <p align="justify">Technology start-ups need full stack developers for their versatility!
    However, as an organization matures a full stack developers can be instrumental in getting
    the specialists all rowing in synchronized harmony.</p>

  <p align="justify">I'm not sure you can call yourself a full stack developer until you have worked
    in multiple languages, platforms, and even industries in your professional career.
    Full stack goes beyond a "senior engineer" as it is along the same lines as a
    polyglot programmer but with a higher view of all the connecting pieces.
    Note that on the above list, only items 3, 4, and 5 actually involve writing code.</p>

  <p align="justify">Clearly, it takes years of work experience in different languages, roles, and
    industries to reach this level of qualification. Because of this, full stack developers
    are few and far between, making those who exist very employable and in-demand.


  </p>

  <p align="justify">In deep self-reflection I can honestly say that according to the above definitions
    I could indeed actually be a qualified full stack developer.

  <p align="justify">&nbsp;</p>

  <p align="justify">&nbsp;</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Employer Introduction Site - Help') %>

<div class="jumbotron"  style="background:#5C81AB !important" >
  <BR>
  <h1>Help Page</h1>

 <p align="justify">The purpose for this website is to prove my
  proficiency in both Ruby, Ruby on Rails and
  cloud adminstration. In this case the cloud is Amazon Web Services.</p>

  <p align="justify">The main reason for employers to login is to demonstrate both
  web site access control, user authentication and email address verification,
  in combination with the mySQL database storage of users.</p>

  <p align="justify">Used in this application were, Ruby, Ruby on Rails with a remote cloud hosted
    mySQL database implementation using RDS on AWS. This means your development system and your
    production system can be hosted in a common cloud location.</p>

  <p align="justify">The gems used in this application are aws-sdk, aws-ses, bcrypt, bootstrap-sass,
    bootstrap-will_paginate, coffee-rails, faker, figaro, guard-minitest, jbuilder, jquery-rails,
    json, mini_backtrace, minitest-reporters, mysql3, rails,
    rspec, sass-rails, sdoc, spring, turbolinks, uglifier, web-consol, and will_paginate</p>

  <p align="justify">The app is hosted on a Ubuntu EC2 instance. The native AWS instance domain name is http://ec2-52-7-56-224.compute-1.amazonaws.com . The http://actually-qualified.com domain name is routed using AWS "Route 53" service.</p>


</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Employer Introduction Site - Home') %>

<div class="jumbotron" style="background:#FFFFE0 !important">

  <h1 style="align-content: center">Employer Introduction Website</h1>

  <h2 style="align-content: center">hosted on</h2>

  <h1 style="align-content: center">Amazon Web Services</h1>

  <div style="text-align: center">
  <p>Welcome, Mark Hanna is actively searching for an exciting employment opportunity.</p>
  <p>Please explore the links above to learn more.</p>
  <p>Registering is quick, easy and demonstrates additional features. <br></p>


    <%= link_to 'Employers Please Register!', signup_path, class: 'btn btn-lg btn-primary'  %>
  </div>
</div>

app/views/static_pages/resume.html.erb
Mark-Hanna-resume-06-19-2015lo.html

app/views/static_pages/simular.html.erb
<% provide(:title, 'Employer Introduction Site - Use The Right Tool for the Job') %>

<div class="jumbotron" style="background:#FFFFE0 !important">


  <h1>Experience takes time to Acquire</h1>

  <h3 align="center" style="color:#000000">Experience helps us to choose the "Right Tool" for each job.</h3>


  <p align=justify>The typical computer code is used to manipulate, convey and store characters, words, and numbers. It
    is mostly all the same, the differences are mostly in the syntax. You must however be aware of what precision is
    required to satisfy each language In the examples below I will attempt to show how my experience and
    versatility can be a benefit to your company. The examples below will illustrate just how simular the different
    languages
    can be.</p>

  <H1>Programming Language: C<br>Is it the Right Tool?</H1>

  <p align=justify>To use an array in C you must first declare it then you can initialize or place values in it.</p>

<pre>
/* IN C comments are contained between these sigils */

/* declare an array of type int called my_array_name which has a maximum number of 10 members */
int my_array_name[10];

/* initialize the my_array_name array with 5 values */
int my_array_name[5] = {1000, 2, 3, 7, 50};
</pre>

  <br><br><br>

  <H1>Programming Language: C++<br>Is it the Right Tool?</H1>

  <p align=justify>To use an array in C++ you also must first declare it then
    you can initialize or place values in it. The C programming language was written by
    AT&T in the 1970's, whereas C with Classes was renamed C++ in 1983. It was both
    very different but very familiar as well.</p>

<pre>
/* IN C++ comments are contained between these sigils */

/* declare an array of type double called my_name_array which has a maximum number of 10 members */
int my_array_name[10];

/* initialize the my_array_name  array with 5 values */
int my_array_name[5] = {1000, 2, 3, 7, 50};
</pre>

  <br><br><br>

  <H1>Programming Language: Java<br>Is it the Right Tool?</H1>

  <p align=justify>To use an array in Java ... an array as with everything in Java must be included within a Class. You
    also must first
    declare it then you can initialize or place values in it. </p>

<pre>
// comments in Java are behind the // sigil

// Java is all about the Classes

class Testarray1{
  public static void main(String args[]){

  //declaration, instantiation and initialization

  int myArrayName[]={1000, 2, 3, 7, 50};

  //if I wanted to print out the array

  //length is the property of array  myArrayName.length

  for (int i=0; i < int myArrayName.length ;i++)
    System.out.println(int myArrayName[i]);
  }
}
</pre>


  <br><br><br>

  <H1>Programming Language: PERL<br>Is it the Right Tool?</H1>

  <p align=justify>PERL is an example of loosely typed language.
    To use an array in PERL you DO NOT need to pre-declare it. ...
    You may declare and initialize it with values in one statement.</p>

<pre>
# Comments in PERL follow the # character

@my_array_name = (1000, 2, 3, 7, 50);

# the line below creates the same array
@my_array_name = qw/1000 2 3 7 50/;

@my_array_name = qw/This is an array/;

@my_array_name = ("This", "is", "an", "array");
</pre>


  <br><br><br>

  <H1>Programming Language: Ruby<br>Is it the Right Tool?</H1>

  <p align=justify>The syntax of Ruby is written in C. The creator blended parts of his
    favorite languages (Perl, Smalltalk, Eiffel, Ada, and Lisp) to form a new
    language that balanced functional programming with imperative programming.
    Class and method definitions are signaled by keywords. In contrast to Perl,
    variables are not obligatorily prefixed with a sigil. When used,
    the sigil changes the semantics of scope of the variable.
    RUBY is another example of loosely typed language, however in
    RUBY everything is an object. RUBY is flexible in
    RUBY you can use an array literal.
    In programming, a "literal" is a type of variable that's
    built into the language itself and has special syntax to create it.
    For example, 3 is a numeric literal and "Ruby" is a string literal.
    An array literal is a list of variables enclosed in square brackets
    and separated by commas, like [ 1, 2, 3 ]. Note that any type of
    variables can be stored in an array,
    including variables of different types in the same array.
   </p>

<pre>
# Comments in RUBY also follow the # character

my_array_name = [1000, 2, 3, 7, 50];

# To use an array in RUBY you DO NOT need to declare it, but you can if you want to
# You can declare or create an empty array my_array_name = Array.new

my_array_name = Array.new

# this line below would place 200 in the 2nd position of the array called  my_array_name
# arrays positions are 0 based i.e.  [0], [1], [2], [3], [4]

my_array_name[1] = 200

#  my_array_name would then = [1000, 200, 3, 7, 50]

</pre>


  <br><br><br>

  <H1>Programming Language: PHP<br>Is it the Right Tool?</H1>

  <p align=justify>PHP is powerful enough to be at the core of the biggest blogging system on the web (WordPress)!
    It is deep enough to run the largest social network (Facebook)!
    PHP is a widely-used server side open source scripting language. Note that any type of
    variables can be stored in an array, including variables of different types in the same array.

<pre>
// This is a single-line comment

# This is also a single-line comment

/*
This is a multiple-lines comment block
that spans over multiple
lines
*/

// You can also use comments to leave out parts of a code line
// below $x would end up being assigned the value of 10     5 + 5
$x = 5 /* + 15 */ + 5;

  <?php
$my_array_name = array(1000, 2, 3, 7, 50);
// the line below assigns $arrlength a value of 5 the number of items in the array
$arrlength = count($my_array_name);

// to print the items contained in the array
for($x = 0; $x < $arrlength; $x++) {
    echo $my_array_name[$x];
    echo "<br>";
}
?>
</pre>

  <br><br><br>

  <H1>Programming Language: Python<br>Is it the Right Tool?</H1>

  <p align=justify>In Python there is a builtin "Array" module which defines an object type which can compactly
    represent an array of
    basic values: characters, integers, floating point numbers. Arrays are sequence
    types and behave very much like lists, except that the type of objects stored in
    them is constrained. The type is specified at object creation time by using a
    <em class="dfn">type code</em>, which is a single character. The following type codes are
    defined:</p>
  <table align=center border="1" class="docutils">
    <colgroup>
      <col width="16%"/>
      <col width="23%"/>
      <col width="28%"/>
      <col width="33%"/>
    </colgroup>
    <thead valign="bottom">
    <tr class="row-odd">
      <th class="head">Type code</th>
      <th class="head">C Type</th>
      <th class="head">Python Type</th>
      <th class="head">Minimum size in bytes</th>
    </tr>
    </thead>
    <tbody valign="top">
    <tr class="row-even">
      <td><tt class="docutils literal"><span class="pre">'c'</span></tt></td>
      <td>char</td>
      <td>character</td>
      <td>1</td>
    </tr>
    <tr class="row-odd">
      <td><tt class="docutils literal"><span class="pre">'b'</span></tt></td>
      <td>signed char</td>
      <td>int</td>
      <td>1</td>
    </tr>
    <tr class="row-even">
      <td><tt class="docutils literal"><span class="pre">'B'</span></tt></td>
      <td>unsigned char</td>
      <td>int</td>
      <td>1</td>
    </tr>
    <tr class="row-odd">
      <td><tt class="docutils literal"><span class="pre">'u'</span></tt></td>
      <td>Py_UNICODE</td>
      <td>Unicode character</td>
      <td>2 (see note)</td>
    </tr>
    <tr class="row-even">
      <td><tt class="docutils literal"><span class="pre">'h'</span></tt></td>
      <td>signed short</td>
      <td>int</td>
      <td>2</td>
    </tr>
    <tr class="row-odd">
      <td><tt class="docutils literal"><span class="pre">'H'</span></tt></td>
      <td>unsigned short</td>
      <td>int</td>
      <td>2</td>
    </tr>
    <tr class="row-even">
      <td><tt class="docutils literal"><span class="pre">'i'</span></tt></td>
      <td>signed int</td>
      <td>int</td>
      <td>2</td>
    </tr>
    <tr class="row-odd">
      <td><tt class="docutils literal"><span class="pre">'I'</span></tt></td>
      <td>unsigned int</td>
      <td>long</td>
      <td>2</td>
    </tr>
    <tr class="row-even">
      <td><tt class="docutils literal"><span class="pre">'l'</span></tt></td>
      <td>signed long</td>
      <td>int</td>
      <td>4</td>
    </tr>
    <tr class="row-odd">
      <td><tt class="docutils literal"><span class="pre">'L'</span></tt></td>
      <td>unsigned long</td>
      <td>long</td>
      <td>4</td>
    </tr>
    <tr class="row-even">
      <td><tt class="docutils literal"><span class="pre">'f'</span></tt></td>
      <td>float</td>
      <td>float</td>
      <td>4</td>
    </tr>
    <tr class="row-odd">
      <td><tt class="docutils literal"><span class="pre">'d'</span></tt></td>
      <td>double</td>
      <td>float</td>
      <td>8</td>
    </tr>
    </tbody>
  </table>

  <br><br>

<pre>

# comments follow the # sigil in Python

# the line below both defines and populates an array of integers in my_array_name
my_name_array = array('I', [1000, 2, 3, 7, 50])

# To print the items in my_array_name you can use a for loop
for i in range(len(my_name_array)):
  print i, my_name_array[i]

</pre>

  <br><br><br>

  <H1>Using the Right Tool...</H1>

  <p align=justify>As you can see being able to read and write computer code varies a little from language to
    language
    but it is not rocket science. Knowing how each language handles things differently is a benefit.
    Even a back yard car mechanic knows you need the right tool for the right job. However if all
    a programmer knows are tools contained in a single toolbox then how will he know the best
    tool to use.
  </p>


  <p align=justify>Languages may look simular but will they all perform the same? No.</p>

  <br><br><br>

  <h1><%= link_to 'Programming Language Differences Click Here', languages_path  %></h1>

  <br><br><br><br><br><br><br><br>


</div>