config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get 'resume' => 'static_pages#resume'
  get 'mission' => 'static_pages#mission'
  get 'simular' => 'static_pages#simular'
  get 'languages' => 'static_pages#languages'
  get 'fsd' => 'static_pages#fsd'
  get 'code' => 'static_pages#code'
  get 'aws' => 'static_pages#aws'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'edit' => 'edit#new'
  get 'four_oh_four' => 'static_pages#home'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  #This is a catchall for 404's
  match '*_path', to: 'static_pages#home', :via => 'get'

end

#
# The priority is used upon order of creation: first created -> highest priority.
# See how all your routes lay out with "rake routes".

# You can have the root of your site routed with "root"

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  <a href="https://www.google.com/#tbm=nws&q=Amazon+Web+Services">The Latest News about Amazon Web Services</a>

  </small>
  <nav>
    <ul>
      <!--
      <li><%= link_to 'About Mark Hanna',   about_path %> &nbsp;&nbsp;| </li>
      -->

      <li><%= link_to 'Contact Mark Hanna', contact_path %></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_google_analytics.html.erb
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-64272628-1', 'auto');
    ga('send', 'pageview')
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background:#364E6A !important">


  <table align="center" width="850px">
    <tr>
      <td align="right" style="white-space:nowrap; width:300px">
        <timeclock>Time is ticking ... &nbsp;</timeclock>
      </td>
      <td align="center" style="white-space:nowrap; width:250px">
        <!--
        Created by mark on 5/20/15.
        This javascript function is located in the /app/assets/javascripts/time_clock_for_header.js
        creates a clock in the format of
        SAT MAY 11 2015 16:00:43    counting up by seconds
        called by div id='clockid'
        -->
        <timeclock>
          <div id='clockid'></div>
        </timeclock>
      </td>
      <td align="left" style="white-space:nowrap; width:300px">
        <timeclock>&nbsp;&nbsp;&nbsp;Mark Hanna is the right choice.</timeclock>
      </td>
    </tr>
  </table>

  <%= link_to 'Ruby on Rails', root_path, id: 'logo' %>

  <nav>
    <ul class="nav navbar-nav navbar-right">

      <% if logged_in? %>
          <li><%= link_to 'Home', root_path, id: 'pagelink' unless current_page?(:action => 'home', :controller => 'static_pages') %></li>
          <li><%= link_to 'Mission', mission_path, id: 'pagelink' unless current_page?(:action => 'mission', :controller => 'static_pages') %></li>
          <li><%= link_to 'Contact', contact_path, id: 'pagelink' unless current_page?(:action => 'contact', :controller => 'static_pages') %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" id="pagelink" data-toggle="dropdown">AWS Info<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Amazon Web Services', aws_path %></li>
              <li><a href="https://www.google.com/#tbm=nws&q=Amazon+Web+Services" target="_blank">Latest AWS News</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" id="pagelink" data-toggle="dropdown">Resume / Info<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Resume', resume_path unless current_page?(:action => 'resume', :controller => 'static_pages') %>
              </li>
              <li>
                <%= link_to 'Full Stack Developer', fsd_path unless current_page?(:action => 'fsd', :controller => 'static_pages')  %>
              </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" id="pagelink" data-toggle="dropdown">Use the Right Tools<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Codes', code_path unless current_page?(:action => 'code', :controller => 'static_pages')  %>
              </li>
              <li>
                <%= link_to 'Simular Looks', simular_path unless current_page?(:action => 'simular', :controller => 'static_pages')  %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to 'Use the Right Tools', languages_path  unless current_page?(:action => 'languages', :controller => 'static_pages')  %>
              </li>
              <li>
                <%= link_to 'Download Source | Git Repository', 'https://github.com/mhanna1/Actually-Qualified' , target: '_blank' %>
              </li>

            </ul>
          </li>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" id="pagelink" data-toggle="dropdown">Account<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Password Reset', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to 'Log out', logout_path, method: 'delete' %>
              </li>
            </ul>
          </li>
      <% else %>
          <li>
            <%= link_to 'Home', root_path, id: 'pagelink' unless current_page?(:action => 'home', :controller => 'static_pages') %>
          </li>
          <li>
            <%= link_to 'Mission', mission_path, id: 'pagelink' unless current_page?(:action => 'mission', :controller => 'static_pages') %>
          </li>
          <li>
            <%= link_to 'Contact', contact_path, id: 'pagelink' unless current_page?(:action => 'contact', :controller => 'static_pages') %>
          </li>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" id="pagelink" data-toggle="dropdown">AWS Info<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Amazon Web Services', aws_path %></li>
              <li><a href="https://www.google.com/#tbm=nws&q=Amazon+Web+Services" target="_blank">Latest AWS News</a></li>
            </ul>
          </li>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" id="pagelink" data-toggle="dropdown">Resume / Info<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Resume', resume_path unless current_page?(:action => 'resume', :controller => 'static_pages')  %>
              </li>
              <li>
                <%= link_to 'Full Stack Developer', fsd_path unless current_page?(:action => 'fsd', :controller => 'static_pages')  %>
              </li>
            </ul>
          </li>

          <li><%= link_to 'Log in', login_path, id: 'pagelink' %></li>
      <% end %>
    </ul>
  </nav>

  <br>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<style type="text/css" id="custom-background-css">
    body.custom-background-css {
        background-color: #9FAFEE;
    }
</style>
<body class=="custom-background-css">
<%= render 'layouts/header' %>
<div class="container" style="background:#9FAFEE !important">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
<%= render 'layouts/google_analytics' if Rails.env.production? %>
</body>
</html>